// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.dream.domain;

import com.sut.dream.domain.Kong;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Kong_Roo_Configurable {
    
    declare @type: Kong: @Configurable;
    
}
